// Demo data for MealSnap portfolio demonstration
// This composable provides realistic dummy data for the demo user

export function useDemoData() {
  // Generate dynamic dates for realistic demo data
  const today = new Date()
  const formatDate = (daysOffset: number) => {
    const date = new Date(today)
    date.setDate(date.getDate() + daysOffset)
    return date.toISOString()
  }

  const formatTime = (daysOffset: number, hour: number, minute: number = 0) => {
    const date = new Date(today)
    date.setDate(date.getDate() + daysOffset)
    date.setHours(hour, minute, 0, 0)
    return date.toISOString()
  }

  // Demo meals data spanning 7 days
  const demoMeals = [
    // TODAY
    {
      id: '1',
      user_id: 'demo',
      name: 'Greek Yogurt with Berries',
      meal_type: 'breakfast',
      consumed_at: formatTime(0, 8),
      total_calories: 220,
      total_protein: 15,
      total_carbs: 30,
      total_fat: 5,
      total_fiber: 4,
      total_sugar: 20,
      notes: 'Greek yogurt topped with mixed berries and honey',
      created_at: formatDate(0),
      updated_at: formatDate(0),
    },
    {
      id: '2',
      user_id: 'demo',
      name: 'Grilled Chicken Caesar Salad',
      meal_type: 'lunch',
      consumed_at: formatTime(0, 12),
      total_calories: 450,
      total_protein: 35,
      total_carbs: 25,
      total_fat: 18,
      total_fiber: 8,
      total_sugar: 6,
      notes: 'Grilled chicken breast over romaine with parmesan',
      created_at: formatDate(0),
      updated_at: formatDate(0),
    },
    {
      id: '3',
      user_id: 'demo',
      name: 'Apple with Almond Butter',
      meal_type: 'snack',
      consumed_at: formatTime(0, 15),
      total_calories: 180,
      total_protein: 6,
      total_carbs: 25,
      total_fat: 8,
      total_fiber: 5,
      total_sugar: 18,
      notes: 'Medium apple with 1 tbsp almond butter',
      created_at: formatDate(0),
      updated_at: formatDate(0),
    },
    {
      id: '4',
      user_id: 'demo',
      name: 'Salmon with Quinoa',
      meal_type: 'dinner',
      consumed_at: formatTime(0, 19),
      total_calories: 520,
      total_protein: 38,
      total_carbs: 45,
      total_fat: 22,
      total_fiber: 6,
      total_sugar: 8,
      notes: 'Baked salmon with quinoa and roasted vegetables',
      created_at: formatDate(0),
      updated_at: formatDate(0),
    },

    // YESTERDAY
    {
      id: '5',
      user_id: 'demo',
      name: 'Overnight Oats',
      meal_type: 'breakfast',
      consumed_at: formatTime(-1, 7, 30),
      total_calories: 280,
      total_protein: 12,
      total_carbs: 48,
      total_fat: 8,
      total_fiber: 6,
      total_sugar: 15,
      notes: 'Oats with banana, chia seeds, and almond milk',
      created_at: formatDate(-1),
      updated_at: formatDate(-1),
    },
    {
      id: '6',
      user_id: 'demo',
      name: 'Turkey Sandwich',
      meal_type: 'lunch',
      consumed_at: formatTime(-1, 12, 30),
      total_calories: 380,
      total_protein: 28,
      total_carbs: 42,
      total_fat: 12,
      total_fiber: 4,
      total_sugar: 8,
      notes: 'Whole grain bread with turkey, avocado, and veggies',
      created_at: formatDate(-1),
      updated_at: formatDate(-1),
    },
    {
      id: '7',
      user_id: 'demo',
      name: 'Mixed Nuts',
      meal_type: 'snack',
      consumed_at: formatTime(-1, 15, 30),
      total_calories: 160,
      total_protein: 6,
      total_carbs: 8,
      total_fat: 14,
      total_fiber: 3,
      total_sugar: 2,
      notes: 'Handful of almonds, walnuts, and cashews',
      created_at: formatDate(-1),
      updated_at: formatDate(-1),
    },
    {
      id: '8',
      user_id: 'demo',
      name: 'Chicken Stir Fry',
      meal_type: 'dinner',
      consumed_at: formatTime(-1, 19, 30),
      total_calories: 420,
      total_protein: 32,
      total_carbs: 35,
      total_fat: 18,
      total_fiber: 5,
      total_sugar: 12,
      notes: 'Chicken with mixed vegetables over brown rice',
      created_at: formatDate(-1),
      updated_at: formatDate(-1),
    },

    // DAY -2
    {
      id: '9',
      user_id: 'demo',
      name: 'Scrambled Eggs & Toast',
      meal_type: 'breakfast',
      consumed_at: formatTime(-2, 8),
      total_calories: 320,
      total_protein: 18,
      total_carbs: 28,
      total_fat: 16,
      total_fiber: 3,
      total_sugar: 4,
      notes: 'Two eggs with whole grain toast and avocado',
      created_at: formatDate(-2),
      updated_at: formatDate(-2),
    },
    {
      id: '10',
      user_id: 'demo',
      name: 'Quinoa Buddha Bowl',
      meal_type: 'lunch',
      consumed_at: formatTime(-2, 13),
      total_calories: 480,
      total_protein: 18,
      total_carbs: 65,
      total_fat: 18,
      total_fiber: 8,
      total_sugar: 10,
      notes: 'Quinoa with chickpeas, vegetables, and tahini dressing',
      created_at: formatDate(-2),
      updated_at: formatDate(-2),
    },
    {
      id: '11',
      user_id: 'demo',
      name: 'Protein Smoothie',
      meal_type: 'snack',
      consumed_at: formatTime(-2, 16),
      total_calories: 220,
      total_protein: 25,
      total_carbs: 18,
      total_fat: 6,
      total_fiber: 4,
      total_sugar: 14,
      notes: 'Protein powder with banana and spinach',
      created_at: formatDate(-2),
      updated_at: formatDate(-2),
    },
    {
      id: '12',
      user_id: 'demo',
      name: 'Beef Tacos',
      meal_type: 'dinner',
      consumed_at: formatTime(-2, 19),
      total_calories: 540,
      total_protein: 35,
      total_carbs: 38,
      total_fat: 25,
      total_fiber: 6,
      total_sugar: 5,
      notes: 'Lean beef tacos with corn tortillas and salsa',
      created_at: formatDate(-2),
      updated_at: formatDate(-2),
    },

    // DAY -3
    {
      id: '13',
      user_id: 'demo',
      name: 'Smoothie Bowl',
      meal_type: 'breakfast',
      consumed_at: formatTime(-3, 8, 30),
      total_calories: 300,
      total_protein: 8,
      total_carbs: 55,
      total_fat: 10,
      total_fiber: 8,
      total_sugar: 35,
      notes: 'Acai bowl with granola, banana, and berries',
      created_at: formatDate(-3),
      updated_at: formatDate(-3),
    },
    {
      id: '14',
      user_id: 'demo',
      name: 'Tuna Salad Wrap',
      meal_type: 'lunch',
      consumed_at: formatTime(-3, 12),
      total_calories: 350,
      total_protein: 25,
      total_carbs: 35,
      total_fat: 12,
      total_fiber: 5,
      total_sugar: 4,
      notes: 'Tuna salad in whole wheat wrap with vegetables',
      created_at: formatDate(-3),
      updated_at: formatDate(-3),
    },
    {
      id: '15',
      user_id: 'demo',
      name: 'Hummus & Veggies',
      meal_type: 'snack',
      consumed_at: formatTime(-3, 15),
      total_calories: 140,
      total_protein: 6,
      total_carbs: 16,
      total_fat: 8,
      total_fiber: 4,
      total_sugar: 6,
      notes: 'Hummus with carrot sticks and bell peppers',
      created_at: formatDate(-3),
      updated_at: formatDate(-3),
    },
    {
      id: '16',
      user_id: 'demo',
      name: 'Grilled Salmon',
      meal_type: 'dinner',
      consumed_at: formatTime(-3, 18, 30),
      total_calories: 480,
      total_protein: 42,
      total_carbs: 25,
      total_fat: 22,
      total_fiber: 4,
      total_sugar: 5,
      notes: 'Grilled salmon with sweet potato and asparagus',
      created_at: formatDate(-3),
      updated_at: formatDate(-3),
    },

    // DAY -4
    {
      id: '17',
      user_id: 'demo',
      name: 'Avocado Toast',
      meal_type: 'breakfast',
      consumed_at: formatTime(-4, 7, 45),
      total_calories: 280,
      total_protein: 8,
      total_carbs: 32,
      total_fat: 16,
      total_fiber: 8,
      total_sugar: 2,
      notes: 'Sourdough toast with mashed avocado and tomato',
      created_at: formatDate(-4),
      updated_at: formatDate(-4),
    },
    {
      id: '18',
      user_id: 'demo',
      name: 'Chicken & Rice Bowl',
      meal_type: 'lunch',
      consumed_at: formatTime(-4, 13, 30),
      total_calories: 520,
      total_protein: 38,
      total_carbs: 48,
      total_fat: 18,
      total_fiber: 3,
      total_sugar: 6,
      notes: 'Grilled chicken with jasmine rice and steamed broccoli',
      created_at: formatDate(-4),
      updated_at: formatDate(-4),
    },
    {
      id: '19',
      user_id: 'demo',
      name: 'Greek Yogurt',
      meal_type: 'snack',
      consumed_at: formatTime(-4, 16, 30),
      total_calories: 120,
      total_protein: 15,
      total_carbs: 8,
      total_fat: 3,
      total_fiber: 0,
      total_sugar: 8,
      notes: 'Plain Greek yogurt with a drizzle of honey',
      created_at: formatDate(-4),
      updated_at: formatDate(-4),
    },
    {
      id: '20',
      user_id: 'demo',
      name: 'Vegetarian Pasta',
      meal_type: 'dinner',
      consumed_at: formatTime(-4, 19, 15),
      total_calories: 460,
      total_protein: 16,
      total_carbs: 68,
      total_fat: 14,
      total_fiber: 6,
      total_sugar: 8,
      notes: 'Whole wheat pasta with marinara and vegetables',
      created_at: formatDate(-4),
      updated_at: formatDate(-4),
    },

    // DAY -5
    {
      id: '21',
      user_id: 'demo',
      name: 'Protein Pancakes',
      meal_type: 'breakfast',
      consumed_at: formatTime(-5, 8, 15),
      total_calories: 340,
      total_protein: 22,
      total_carbs: 35,
      total_fat: 12,
      total_fiber: 4,
      total_sugar: 12,
      notes: 'Protein pancakes with banana and maple syrup',
      created_at: formatDate(-5),
      updated_at: formatDate(-5),
    },
    {
      id: '22',
      user_id: 'demo',
      name: 'Mediterranean Salad',
      meal_type: 'lunch',
      consumed_at: formatTime(-5, 12, 45),
      total_calories: 420,
      total_protein: 14,
      total_carbs: 28,
      total_fat: 28,
      total_fiber: 6,
      total_sugar: 8,
      notes: 'Mixed greens with feta, olives, and olive oil dressing',
      created_at: formatDate(-5),
      updated_at: formatDate(-5),
    },
    {
      id: '23',
      user_id: 'demo',
      name: 'Trail Mix',
      meal_type: 'snack',
      consumed_at: formatTime(-5, 15, 45),
      total_calories: 180,
      total_protein: 5,
      total_carbs: 18,
      total_fat: 12,
      total_fiber: 3,
      total_sugar: 10,
      notes: 'Mixed nuts, seeds, and dried fruit',
      created_at: formatDate(-5),
      updated_at: formatDate(-5),
    },
    {
      id: '24',
      user_id: 'demo',
      name: 'Pork Chop Dinner',
      meal_type: 'dinner',
      consumed_at: formatTime(-5, 18, 45),
      total_calories: 580,
      total_protein: 45,
      total_carbs: 32,
      total_fat: 28,
      total_fiber: 4,
      total_sugar: 6,
      notes: 'Lean pork chop with mashed potatoes and green beans',
      created_at: formatDate(-5),
      updated_at: formatDate(-5),
    },

    // DAY -6
    {
      id: '25',
      user_id: 'demo',
      name: 'Breakfast Burrito',
      meal_type: 'breakfast',
      consumed_at: formatTime(-6, 8),
      total_calories: 380,
      total_protein: 20,
      total_carbs: 35,
      total_fat: 18,
      total_fiber: 4,
      total_sugar: 3,
      notes: 'Eggs, cheese, and salsa in whole wheat tortilla',
      created_at: formatDate(-6),
      updated_at: formatDate(-6),
    },
    {
      id: '26',
      user_id: 'demo',
      name: 'Sushi Bowl',
      meal_type: 'lunch',
      consumed_at: formatTime(-6, 13, 15),
      total_calories: 450,
      total_protein: 22,
      total_carbs: 58,
      total_fat: 12,
      total_fiber: 2,
      total_sugar: 8,
      notes: 'Salmon sashimi over sushi rice with vegetables',
      created_at: formatDate(-6),
      updated_at: formatDate(-6),
    },
    {
      id: '27',
      user_id: 'demo',
      name: 'Cheese & Crackers',
      meal_type: 'snack',
      consumed_at: formatTime(-6, 16),
      total_calories: 200,
      total_protein: 8,
      total_carbs: 18,
      total_fat: 12,
      total_fiber: 2,
      total_sugar: 2,
      notes: 'Whole grain crackers with aged cheddar',
      created_at: formatDate(-6),
      updated_at: formatDate(-6),
    },
    {
      id: '28',
      user_id: 'demo',
      name: 'BBQ Chicken',
      meal_type: 'dinner',
      consumed_at: formatTime(-6, 19, 30),
      total_calories: 520,
      total_protein: 40,
      total_carbs: 28,
      total_fat: 22,
      total_fiber: 3,
      total_sugar: 15,
      notes: 'BBQ chicken breast with corn and coleslaw',
      created_at: formatDate(-6),
      updated_at: formatDate(-6),
    },
  ]

  // Demo progress data
  const demoProgress = [
    {
      id: '1',
      user_id: 'demo',
      date: formatDate(0).split('T')[0],
      total_calories: 1370,
      total_protein: 94,
      total_carbs: 125,
      total_fat: 53,
      created_at: formatDate(0),
    },
    {
      id: '2',
      user_id: 'demo',
      date: formatDate(-1).split('T')[0],
      total_calories: 1240,
      total_protein: 78,
      total_carbs: 133,
      total_fat: 52,
      created_at: formatDate(-1),
    },
    {
      id: '3',
      user_id: 'demo',
      date: formatDate(-2).split('T')[0],
      total_calories: 1560,
      total_protein: 96,
      total_carbs: 149,
      total_fat: 67,
      created_at: formatDate(-2),
    },
    {
      id: '4',
      user_id: 'demo',
      date: formatDate(-3).split('T')[0],
      total_calories: 1270,
      total_protein: 81,
      total_carbs: 131,
      total_fat: 52,
      created_at: formatDate(-3),
    },
    {
      id: '5',
      user_id: 'demo',
      date: formatDate(-4).split('T')[0],
      total_calories: 1380,
      total_protein: 77,
      total_carbs: 156,
      total_fat: 51,
      created_at: formatDate(-4),
    },
    {
      id: '6',
      user_id: 'demo',
      date: formatDate(-5).split('T')[0],
      total_calories: 1520,
      total_protein: 86,
      total_carbs: 113,
      total_fat: 80,
      created_at: formatDate(-5),
    },
    {
      id: '7',
      user_id: 'demo',
      date: formatDate(-6).split('T')[0],
      total_calories: 1550,
      total_protein: 90,
      total_carbs: 139,
      total_fat: 64,
      created_at: formatDate(-6),
    },
  ]

  // Demo user goals
  const demoGoals = {
    id: '1',
    user_id: 'demo',
    target_calories: 2000,
    target_protein: 150,
    target_carbs: 250,
    target_fat: 65,
    start_date: formatDate(-30).split('T')[0],
    is_active: true,
    created_at: formatDate(-30),
    updated_at: formatDate(0),
  }

  // Demo user profile
  const demoUser = {
    id: 'demo',
    email: useRuntimeConfig().public.demoEmail || 'demo@mealsnap.app',
    name: 'Demo User',
    height: 170,
    weight: 70,
    age: 30,
    activity_level: 'moderate',
    goal: 'maintain',
    daily_calorie_target: 2000,
    created_at: formatDate(-30),
    updated_at: formatDate(0),
  }

  return {
    demoMeals,
    demoProgress,
    demoGoals,
    demoUser,

    // Helper functions for filtered data
    getTodaysMeals: () =>
      demoMeals.filter((meal) =>
        meal.consumed_at.startsWith(formatDate(0).split('T')[0])
      ),
    getTodaysProgress: () =>
      demoProgress.find(
        (progress) => progress.date === formatDate(0).split('T')[0]
      ),
    getActiveGoals: () => demoGoals,
    getRecentMeals: (days: number = 7) => demoMeals.slice(0, days * 4), // 4 meals per day
    getProgressHistory: (days: number = 7) => demoProgress.slice(0, days),
  }
}
